; --- CONFIGURACIONES GLOBALES (Aplican para ambas placas) ---
[env]
framework = arduino
monitor_speed = 115200

; ==========================================================
; ENTORNO 1: TU NUEVO RECEPTOR (XIAO S3 con LoRa y ESP-NOW)
; ==========================================================

[env:receptor_xiao_s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
    mikem/RadioHead @ ^1.120

; ==========================================================
; ENTORNO 2: TU PROYECTO VIEJO DSP (ESP32 Clásico de Steren)
; ==========================================================
[env:dsp_esp32_clasico]
platform = espressif32
board = esp32dev
lib_deps = 
    ; Aquí puedes dejar cualquier librería vieja que usaras para el DSP
    ; adafruit/Adafruit GFX Library @ ^1.11.5 (ejemplo)