; --- CONFIGURACIÓN GENERAL COMÚN ---
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit BNO08x @ ^1.2.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14

; =========================================================================
; ENTORNO PARA EL RETO DE DSP (Puro IMU a 100Hz - Cero bloqueos)
; =========================================================================
[env:dsp_esp32_s3]
board = esp32-s3-devkitm-1
; Le dice a PlatformIO que compile main_dsp.cpp e IGNORE el main de telecom
src_filter = +<*> -<main_telecom.cpp>

; Versión por si tú quieres correr el código de DSP en tu placa Steren
[env:dsp_esp32_steren]
board = esp32dev
src_filter = +<*> -<main_telecom.cpp>


; =========================================================================
; ENTORNO PARA EL RETO DE TELECOMUNICACIONES (Integración de Sensores)
; =========================================================================
[env:telecom_esp32_s3]
board = esp32-s3-devkitm-1
; Le dice a PlatformIO que compile main_telecom.cpp e IGNORE el main de dsp
src_filter = +<*> -<main_dsp.cpp>

; Versión por si quieres probar el ultrasonico en tu placa Steren
[env:telecom_esp32_steren]
board = esp32dev
src_filter = +<*> -<main_dsp.cpp>